#!/bin/bash
set -e

echo "Building smokescreen 💨"
echo ""

rm -rf dist
mkdir -p dist

echo "Compiling for Intel macOS"
GOOS=darwin GOARCH=amd64 go build -o dist/smokescreen-darwin-amd64
chmod +x dist/smokescreen-darwin-amd64
echo "👍  dist/smokescreen-darwin-amd64"
gzip -c dist/smokescreen-darwin-amd64 > dist/smokescreen-darwin-amd64.gz
echo ""

echo "Compiling for arm64 macOS"
GOOS=darwin GOARCH=arm64 go build -o dist/smokescreen-darwin-arm64
chmod +x dist/smokescreen-darwin-arm64
echo "👍  dist/smokescreen-darwin-arm64"
gzip -c dist/smokescreen-darwin-arm64 > dist/smokescreen-darwin-arm64.gz
echo ""

echo "Compiling for Intel Linux"
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o dist/smokescreen-linux-amd64
chmod +x dist/smokescreen-linux-amd64
echo "👍  dist/smokescreen-linux-amd64"
gzip -c dist/smokescreen-linux-amd64 > dist/smokescreen-linux-amd64.gz
echo ""

echo "Compiling for arm Linux"
GOOS=linux GOARCH=arm go build -o dist/smokescreen-linux-arm
chmod +x dist/smokescreen-linux-arm
echo "👍  dist/smokescreen-linux-arm"
gzip -c dist/smokescreen-linux-arm > dist/smokescreen-linux-arm.gz
echo ""

echo "Compiling for arm64 Linux"
GOOS=linux GOARCH=arm64 go build -o dist/smokescreen-linux-arm64
chmod +x dist/smokescreen-linux-arm64
echo "👍  dist/smokescreen-linux-arm64"
gzip -c dist/smokescreen-linux-arm64 > dist/smokescreen-linux-arm64.gz

echo ""
echo "All done! ✅"
